services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --http-port=8081 --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth          # <--- TO JEST KLUCZOWE
      KC_PROXY_HEADERS: xforwarded          # <--- Dodaj to, by Keycloak rozumiał Nginxa
      KC_HOSTNAME_STRICT: "false"
      KC_IMPORT: /opt/keycloak/data/import/realm.json
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
        - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
        - JENKINS_OPTS=--httpPort=8082
    user: root

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs

  gateway:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev

#stawianie środowiska
#docker compose up --build
